Split byte counters into reads and writes
LLNL/RAJAPerf pull request #462
Opened 2024-07-15 04:34 UTC by MrBurmark

# Split byte counters into reads and writes

This PR splits our current bytesPerRep counter into bytes read, bytes written, and bytes atomic modify written (atomicAdd with ignored return value). This will help us to understand performance on hardware where the total bandwidth is not the same as the sum of the read and write bandwidth.

This also messes with the way we decide the actual problem size from the target problem size to be closer to target problem size. It also fixes some cases where we had a zero or negative actual problem size when the target problem size was one. This also tweaks some reported problem sizes to be more consistent across kernels, for example using num_zones in app kernels instead of the number of iterations.

- This PR is a feature
- It does the following:
  - Modifies/refactors all of the bytes counters by splitting them into 3 categories
  - Fixes #457 
  - Adds split byte counts at the request of me

2024-07-15 18:12 UTC, michaelmckinsey1 requested changes
Fixing Caliper variables

2024-07-15 18:12 UTC, michaelmckinsey1 commented on src/common/KernelBase.cpp
> +    cali_set_double(BytesAtomicModifyWritten_Rep_attr,(double)getBytesAtomicModifyWrittenPerRep());
```suggestion
    cali_set_double(Bytes_Read_Rep_attr,(double)getBytesReadPerRep());
    cali_set_double(Bytes_Written_Rep_attr,(double)getBytesWrittenPerRep());
    cali_set_double(Bytes_AtomicModifyWritten_Rep_attr,(double)getBytesAtomicModifyWrittenPerRep());
```
Match variable declarations in `KernelBase.hpp`

2024-07-15 18:30 UTC, pearce8 commented
@MrBurmark How are you counting memory accesses that are a read, followed by a write?

2024-07-15 22:33 UTC, MrBurmark commented
> @MrBurmark How are you counting memory accesses that are a read, followed by a write?

I assume you're talking about something like `x[i] += 1`, that counts as 1 read and 1 write. An `atomicAdd(&x[i], 1)` on the other hand counts as 1 atomic modify write, while previously it would have counted as 1 read and 1 write. I tried to keep the totals the same, so in calculating the total bytes/rep 1 atomic modify write counts as 2.

2024-07-15 23:49 UTC, michaelmckinsey1 approved these changes
I tested the Caliper changes and they are correct.

2024-07-16 05:33 UTC, pearce8 commented
Yes, that's a good example.  I am thinking about the cache: a read followed by a write to the same location will take 1 spot in cache, and will be a single cache miss.  So, I wonder if this should count as 1 operation (perhaps a write) - which would then match the 1 modify-write atomic operation.  From a cache standpoint, each write is technically a read followed by a write, so I think labeling these operations as a write would be appropriate.  Thoughts?

2024-07-16 15:50 UTC, MrBurmark commented
I'm not sure that the data I've seen on GPUs supports that. If that were true then write only kernels should get half of expected bandwidth, but I don't see that.

2024-07-16 20:32 UTC, rhornung67 approved these changes
Thank you @MrBurmark I looked this over pretty carefully, but it's hard to know exactly if the total byte counts here match the previous way of doing this. Is there a reasonable way to check that without doing too much work.

2024-07-16 20:41 UTC, MrBurmark commented
I'll looking at a run with problem size 1M as that is a perfect square and cube, so we should get the same problem size and check that its the same as before. There are a couple where I did make changes because how we counted was wrong or at least inconsistent before though.

2024-07-16 20:47 UTC, MrBurmark commented on src/basic/INDEXLIST_3LOOP.cpp
> +  setBytesAtomicModifyWrittenPerRep( 0 );
I changed Int_type to Index_type here to match the actual usage.

2024-07-16 20:48 UTC, MrBurmark commented on src/basic/MAT_MAT_SHARED.cpp
> +  setBytesWrittenPerRep( 1*sizeof(Real_type) * m_N*m_N  );
I changed the bytes read to 2x because this kernel uses +=

2024-07-16 20:49 UTC, MrBurmark commented on src/basic/REDUCE_STRUCT.cpp
> +  setBytesWrittenPerRep( 6*sizeof(Real_type) );
Added an extra 6 reads as this is a reduction

2024-07-16 20:50 UTC, MrBurmark commented on src/lcals/TRIDIAG_ELIM.cpp
> +  setBytesWrittenPerRep( 1*sizeof(Real_type ) * (m_N-1) );
I changed the meaning of N here to avoid doing zero work.

2024-07-16 20:52 UTC, MrBurmark commented on src/polybench/POLYBENCH_GEMM.cpp
> +  m_nk = Index_type(double(nk_default)/ni_default*m_ni);
Changing m_nk to shrink/grow with problem size changes the actual bytes used

2024-07-16 20:53 UTC, MrBurmark commented on src/apps/CONVECTION3DPA.cpp
> +  setBytesWrittenPerRep( 1*sizeof(Real_type) + CPA_D1D*CPA_D1D*CPA_D1D*m_NE ); // y
changed this to count y as a read and write because there is a +=

2024-07-16 20:54 UTC, MrBurmark commented on src/apps/DIFFUSION3DPA.cpp
> +  setBytesWrittenPerRep( 1*sizeof(Real_type) * DPA_D1D*DPA_D1D*DPA_D1D*m_NE ); // y
count y as read and write due to +=

2024-07-16 20:55 UTC, MrBurmark commented on src/apps/FIR.cpp
> +  setBytesWrittenPerRep( 1*sizeof(Real_type) * getActualProblemSize() );
count the coefficients as bytes read

2024-07-16 20:56 UTC, MrBurmark commented on src/apps/MASS3DPA.cpp
> +  setBytesWrittenPerRep( 1*sizeof(Real_type) * MPA_D1D*MPA_D1D*MPA_D1D*m_NE ); // Y
count y as read and write due to +=

2024-07-16 20:58 UTC, MrBurmark commented on src/apps/PRESSURE.cpp
> +                         1*sizeof(Real_type) * getActualProblemSize() );
add missing read

2024-07-16 20:59 UTC, MrBurmark commented on src/apps/ZONAL_ACCUMULATION_3D.cpp
> +                      1*sizeof(Real_type) * (getItsPerRep() + 1+m_domain->jp+m_domain->kp) );
```suggestion
                      1*sizeof(Real_type) * m_domain->n_real_nodes );
```

2024-07-16 21:01 UTC, MrBurmark commented on src/apps/ZONAL_ACCUMULATION_3D.cpp
> +                      1*sizeof(Real_type) * (getItsPerRep() + 1+m_domain->jp+m_domain->kp) );
fix copy and paste error

2024-07-16 22:59 UTC, merged

2024-07-17 05:33 UTC, michaelmckinsey1 commented
> Thank you @MrBurmark I looked this over pretty carefully, but it's hard to know exactly if the total byte counts here match the previous way of doing this. Is there a reasonable way to check that without doing too much work.

I was curious about this, so I had checked myself and for what it is worth the only kernels that I found that **don't** match (`Bytes/Rep = BytesRead/Rep + BytesWritten/Rep + BytesAtomicModifyWritten/Rep`) are the atomic kernels `Basic_DAXPY_ATOMIC` and `Basic_PI_ATOMIC`. This makes sense because [getBytesPerRep](https://github.com/LLNL/RAJAPerf/blob/0f8942584f0afacf00ce85b1ad89b290de57dcb5/src/common/KernelBase.hpp#L160) has `2*bytes_atomic_modify_written_per_rep` (instead of 1x) to match the old counting. _All of the other kernels match at 1M._

It looks like you already checked this @MrBurmark, but I thought I would let you know since I was looking.

2024-07-17 15:41 UTC, rhornung67 commented
Thank you for checking @michaelmckinsey1

2024-07-17 15:50 UTC, MrBurmark commented
Thanks for the extra set of eyes on that @michaelmckinsey1