Add Algorithmic Complexity Info
LLNL/RAJAPerf pull request #471
Opened 2024-08-09 21:46 UTC by MrBurmark

# Add Algorithmic Complexity Info

Add the ability to print the algorithmic complexity of each kernel.

- This PR is a feature
- It does the following:
  - Adds algorithmic complexity info at the request of me and @pearce8

2024-08-09 21:47 UTC, MrBurmark commented
@michaelmckinsey1 Can you take a look at the caliper stuff, I put a draft in but was completely guessing as to how to add strings.

2024-08-12 22:27 UTC, michaelmckinsey1 requested changes
These changes allow complexity to be recorded as a string with Caliper.

The complexity metric can be read using the `string_attributes=["Complexity"]` argument to `from_caliperreader` for either Hatchet or Thicket.

2024-08-12 22:27 UTC, michaelmckinsey1 commented on src/common/KernelBase.cpp
> +                                           CALI_ATTR_AGGREGATABLE |
```suggestion
```

2024-08-12 22:27 UTC, michaelmckinsey1 commented on src/common/KernelBase.cpp
> +    cali_set_string(Complexity_attr, getComplexityName(getComplexity()));
```suggestion
    cali_set_string(Complexity_attr, getComplexityName(getComplexity()).c_str());
```

2024-08-12 22:27 UTC, michaelmckinsey1 commented on src/common/KernelBase.cpp
>          ]
```suggestion
        ],
        "group by": ["Complexity"],
```

2024-08-12 22:27 UTC, michaelmckinsey1 commented on src/common/KernelBase.cpp
>          ]
```suggestion
        ],
        "group by": ["Complexity"],
```

2024-08-12 23:31 UTC, michaelmckinsey1 approved these changes

2024-08-12 23:41 UTC, MrBurmark commented
Thanks @michaelmckinsey1

2024-08-13 15:59 UTC, rhornung67 approved these changes

2024-08-13 16:00 UTC, merged